# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a846b59c940ab37c518af123b7086859aaddd94ade726b3d8160e51b45f2f17690e8d338e4effaa6b195e256017d00bdcb06b803f6c71ae2fd4f7851533ad6

test:
  secret_key_base: eff044b7927d841319443df94977a6e54b5ac90d41d298ecdd0ebe54f506524c1252d5a66b1da044a424b031f1fd0af2eeac88a03eaff8d96831145d86fb63ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
